import { Conversation, Lead } from "./types";

const msg = (id: string, role: "visitor" | "assistant", text: string, at = "Today, 10:24") => ({ id, role, text, at });

export const seedConversations: Conversation[] = [
  { id:"c1", ticket:"IWP-1037", customer:"Aanya Mehra", department:"Wedding Sales", status:"Open", priority:"High", latest:"We are thinking Jaipur for 250 guests.", summary:"December Jaipur wedding for 250 guests; ₹1.5–2 Cr budget; palace venue preferred.", updatedAt:"4 min", transcript:[msg("m1","visitor","We are planning a Jaipur wedding for 250 guests in December."),msg("m2","assistant","Wonderful. Do you have a working budget range?"),msg("m3","visitor","Around ₹1.5–2 Cr, and we love palace venues.")] },
  { id:"c2", ticket:"IWP-1036", customer:"Rohan & Mira", department:"Wedding Sales", status:"Waiting", priority:"Medium", latest:"Could you share ideas for Goa?", summary:"Exploring a 180-guest beach wedding in Goa; date flexible in February.", updatedAt:"18 min", transcript:[msg("m4","visitor","Could you share ideas for a Goa beach wedding?"),msg("m5","assistant","Absolutely. About how many guests are you expecting?"),msg("m6","visitor","Around 180, likely in February.")] },
  { id:"c3", ticket:"IWP-1034", customer:"Kabir Sethi", department:"Wedding Sales", status:"Open", priority:"Medium", latest:"Udaipur, intimate and elegant.", summary:"Udaipur celebration for 90 guests; intimate lakeside venue; November 2027.", updatedAt:"36 min", transcript:[msg("m7","visitor","We want Udaipur, intimate and elegant, for about 90 guests."),msg("m8","assistant","A lakeside celebration could be beautiful. When are you planning it?"),msg("m9","visitor","November 2027.")] },
  { id:"c4", ticket:"IWP-1032", customer:"Nisha Kapoor", department:"HR and Careers", status:"Open", priority:"Low", latest:"I would like to apply for a role.", summary:"Event producer with four years’ experience asking about career opportunities.", updatedAt:"1 hr", transcript:[msg("m10","visitor","I would like to apply for a role in wedding production."),msg("m11","assistant","I’ve routed your enquiry to HR and Careers. Please share your preferred contact email.")] },
  { id:"c5", ticket:"IWP-1029", customer:"Arjun Rao", department:"HR and Careers", status:"Resolved", priority:"Low", latest:"Is there an internship program?", summary:"Hospitality student enquiring about summer internships.", updatedAt:"3 hr", transcript:[msg("m12","visitor","Is there an internship program for hospitality students?"),msg("m13","assistant","I can prepare this for our HR and Careers team.")] },
  { id:"c6", ticket:"IWP-1027", customer:"Studio Northstar", department:"Vendors and Partnerships", status:"Waiting", priority:"Medium", latest:"We would love to collaborate.", summary:"Fictional wedding photography studio proposing a vendor collaboration.", updatedAt:"Yesterday", transcript:[msg("m14","visitor","I’m a photographer and we would love to collaborate."),msg("m15","assistant","Thank you. I’ll route your portfolio enquiry to Vendors and Partnerships.")] },
  { id:"c7", ticket:"IWP-1025", customer:"Devika Shah", department:"Client Servicing", status:"Open", priority:"High", latest:"Need urgent help with tomorrow’s transfer.", summary:"Existing client needs urgent assistance with a guest airport transfer.", updatedAt:"Yesterday", transcript:[msg("m16","visitor","I’m already a client and need urgent help with tomorrow’s airport transfer."),msg("m17","assistant","I’m prioritising this for Client Servicing now.")] },
  { id:"c8", ticket:"IWP-1021", customer:"Vivan Malhotra", department:"Finance", status:"Waiting", priority:"Medium", latest:"Please resend the invoice.", summary:"Existing enquiry requesting a copy of a demo invoice.", updatedAt:"2 days", transcript:[msg("m18","visitor","I need an invoice copy, please."),msg("m19","assistant","I’ve routed this to Finance for follow-up.")] }
];

export const seedLeads: Lead[] = [
  { id:"l1", name:"Aanya Mehra", contact:"aanya@example.com", destination:"Jaipur", guests:250, budget:"₹1.5–2 Cr", date:"December 2027", venueStyle:"Heritage palace", contactMethod:"WhatsApp", stage:"Qualified", score:92, createdAt:"Today" },
  { id:"l2", name:"Rohan & Mira", contact:"+91 90000 01002", destination:"Goa", guests:180, budget:"₹80L–1.2 Cr", date:"February 2028", venueStyle:"Beach resort", contactMethod:"Phone", stage:"New", score:78, createdAt:"Today" },
  { id:"l3", name:"Kabir Sethi", contact:"kabir@example.com", destination:"Udaipur", guests:90, budget:"₹50–80L", date:"November 2027", venueStyle:"Lakeside", contactMethod:"Email", stage:"Contacted", score:84, createdAt:"Yesterday" },
  { id:"l4", name:"Tara Anand", contact:"tara@example.com", destination:"Jodhpur", guests:320, budget:"₹2 Cr+", date:"January 2028", venueStyle:"Fort", contactMethod:"WhatsApp", stage:"Consultation booked", score:96, createdAt:"3 days ago" },
  { id:"l5", name:"Neil Batra", contact:"+91 90000 01005", destination:"Kerala", guests:140, budget:"₹80L–1.2 Cr", date:"March 2028", venueStyle:"Backwater resort", contactMethod:"Phone", stage:"Proposal sent", score:88, createdAt:"5 days ago" },
  { id:"l6", name:"Ira & Veer", contact:"ira.veer@example.com", destination:"Udaipur", guests:120, budget:"₹1.2–1.5 Cr", date:"October 2027", venueStyle:"Palace", contactMethod:"Email", stage:"Converted", score:98, createdAt:"Last week" }
];
