# Generated by Django 5.2.18 on 2026-10-08 12:55

import concierge.engine
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=20, unique=True)),
                ('customer', models.CharField(default='Website visitor', max_length=120)),
                ('department', models.CharField(choices=[('Wedding Sales', 'Wedding Sales'), ('Client Servicing', 'Client Servicing'), ('HR and Careers', 'HR and Careers'), ('Vendors and Partnerships', 'Vendors and Partnerships'), ('Marketing and PR', 'Marketing and PR'), ('Finance', 'Finance'), ('General Support', 'General Support')], default=concierge.engine.Department['GENERAL'], max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('waiting', 'Waiting'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(default='To be collected', max_length=120)),
                ('destination', models.CharField(default='To be decided', max_length=60)),
                ('guests', models.PositiveIntegerField(default=0)),
                ('budget', models.CharField(default='To be discussed', max_length=60)),
                ('event_date', models.CharField(default='Flexible', max_length=60)),
                ('venue_style', models.CharField(default='To be discussed', max_length=60)),
                ('contact_method', models.CharField(default='To be collected', max_length=30)),
                ('stage', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('contacted', 'Contacted'), ('consultation', 'Consultation booked'), ('proposal', 'Proposal sent'), ('converted', 'Converted')], default='new', max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=60)),
                ('created_at', models.DateTimeField()),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.conversation')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('visitor', 'Visitor'), ('assistant', 'Concierge'), ('agent', 'Staff')], max_length=10)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.conversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
