# Generated by Django 5.2.18 on 2026-10-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='summary_ai',
            field=models.BooleanField(default=False, help_text='Summary written by the language model.'),
        ),
        migrations.AddField(
            model_name='message',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
