# Generated by Django 5.2.18 on 2026-10-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_ai_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('assistant', 'Concierge'), ('agent', 'Staff'), ('system', 'System')], max_length=10),
        ),
    ]
