# Generated by Django 5.2.18 on 2026-10-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_system_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='routed_by',
            field=models.CharField(choices=[('ai', 'Gemini'), ('rules', 'Rules'), ('visitor', 'Visitor')], default='rules', max_length=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='routing_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='routing_reason',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
